knowit/folk-webapp

src/components/DropdownPicker.tsx

- removing height
- align child with margin left

Fixing unaligned selectbox:

---

backend/dataplattform/lib.js
backend/repository/data.js

update data repo to use report api instead of query for better perfor…mance

Feature/fetch data as reports 

---

src/data/components/table/cells/ExperienceCell.tsx

Måtte endre litt når "Se prosjekter" ble Button :)

lowercase on 'se prosjekter' button

---

src/components/Footer.tsx

Måtte legge til mellomrom i footer

added spaces to footer

---

backend/repository/data.js
backend/repository/util.js

remove optional chaining for backend part

---

backend/repository/util.js

tar vekk koden som lagde forvirring i aws

comment out the code that made issues on aws

---

serverless.yml
src/components/Footer.tsx

Revert "Adds emails to footer"

---

backend/repository/data.js

Jeg missforstod litt i går; vi skal ha med begge typer grupperinger, den som stod i issuet og den litt mer detaljerte :)

added another grouping

---

backend/repository/data.js
backend/repository/util.js

Revert "Feature/category endpoint"

---

src/data/components/common.tsx

new colors

---

src/LoginProvider.tsx
src/authToken.tsx

Fornyer accessToken hvert 10 minutt.

added token refresh every ten minutes

---

src/pages/Competence.tsx

Flyttet grafen opp, og fjernet den tomme grafen med samme overskrift

Moved radarChart

---

backend/repository/data.js
backend/repository/util.js

- Added reStructCategories as a helper function
Fixes issue with `employeeRadar` endpoint.

Added reStructCategories as a helper function

---

src/pages/EmployeeSite.tsx

Lagt til barchart på ansattsidene også

barchart on empSite

---

backend/.eslintrc.json
backend/dataplattform/lib.js
backend/middlewares/dataplattform.js
backend/package.json
backend/reporting/index.js
backend/repository/data.js
backend/repository/util.js
backend/routers/api.js
backend/routers/auth.js
backend/routers/handler.js
backend/yarn.lock

- Linting regler #315
- Response header error codes #355
- DEBUG env for verbosity nivå #379
- Error message handling #364
- `data.js` easy rejection #363
- Output warnings #300

Reporting handler, linting, and cleanup

---

backend/repository/data.js
backend/repository/util.js
src/data/components/table/cells/CustomerStatusCell.tsx
src/data/components/table/cells/ProjectStatusCell.tsx
src/pages/EmployeeSite.tsx

Reverts knowit/folk-webapp#154

Revert "Feature/ubw customer data"

---

backend/repository/data.js
backend/repository/util.js
src/data/components/table/cells/CustomerStatusCell.tsx
src/data/components/table/cells/ProjectStatusCell.tsx
src/pages/EmployeeSite.tsx

Reverts knowit/folk-webapp#157

Revert "Revert "Feature/ubw customer data""

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml

`yarn install <package-name>` should be `yarn add <package-name>`

Fixed typo in yarn command

---

src/components/RowCount.tsx
src/data/DDTable.tsx

This shows the count of rows currently being displayed (respecting filtering and search), with the total number of rows next to it.

Feature/421 Show row count

---

backend/routers/auth.js
package.json

Reverts knowit/folk-webapp#194

Revert "Update some config files"

---

backend/package.json
backend/yarn.lock
serverless.yml

lagt til serverless-typescript plugin

lagt til serverless-typescript plugin i backend

---

.husky/pre-commit
src/tests/App.test.tsx
src/tests/CharacterLimitBox.test.tsx
src/tests/EmployeeInfo.test.tsx
src/tests/Header.test.tsx
src/tests/NavMenu.test.tsx

Update pre-commit message and move test to tests folder

---

.husky/pre-commit
src/tests/App.test.tsx
src/tests/CharacterLimitBox.test.tsx
src/tests/EmployeeInfo.test.tsx
src/tests/Header.test.tsx
src/tests/NavMenu.test.tsx

Issue [#512](https://github.com/knowit/Dataplattform-issues/issues/512).
Ekstra:
- Kjapp oppdatering av pre-commit meldinger. ✨ Aesthetics ✨
- Flyttet test-filer til `test/`-mappe i frontend

512 minikort for kunder

---

backend/repository/reports.js

fixes https://github.com/knowit/Dataplattform-issues/issues/520
- Modifiserte rapporten til å telle ikke definerte

Modified AgeDistributionsGroup query to count people with age not defined

---

src/pages/Competence.tsx

Fixes knowit/Dataplattform-issues/issues/502
Fjerner prosjektstatus-tabell fra kompetansefliken

Remove employee table from competence tab

---

src/pages/customer/CustomerDropdown.tsx

fixes knowit/Dataplattform-issues#553

Make customer searchable

---

src/pages/Competence.tsx

fixes https://github.com/knowit/Dataplattform-issues/issues/551
- La til beskrivelse på grafen så det lettere tydes hva som beskrives

Added description to fagaktiviteter

---

backend/repository/data.ts
backend/repository/reports.js
backend/repository/util.ts
src/data/components/table/cells/ProjectStatusCell.tsx

Created a new way to check work status of employees, and updated reports

---

src/data/components/table/cells/ConsultantCell.tsx

fixes https://github.com/knowit/Dataplattform-issues/issues/565
Email blir sendt gjennom data, ikke direkte som en prop da det ble hentet fra samme objekt.

Fixed /ansatte/@email issue

---

backend/routers/employees/aggregationHelpers.ts
backend/routers/employees/employeesAggregation.ts
backend/routers/employees/employeesRouter.ts
backend/routers/employees/employeesTypes.ts
backend/routers/errorHandling.ts
backend/routers/routers.ts

Extensive description here: [#557](https://github.com/knowit/Dataplattform-issues/issues/557).

Employees: Rewrite backend logic

---

backend/routers/competence/competenceRouter.ts
backend/routers/competence/competenceTypes.ts
src/api/client.ts

Extensive description here: [#557](https://github.com/knowit/Dataplattform-issues/issues/557).

Add competenceFilter to router

---

src/pages/EmployeeSite.tsx

Sizingen av employeesite charten ble feil.

Fixed sizing of chart employeesite

---

src/api/data/competence/competenceApi.ts
src/components/EmployeeTable.tsx
src/components/FilterInput.tsx
src/components/FilterUtil.tsx
src/data/DDTable.tsx
src/data/types.tsx
src/pages/customer/CustomerFilter.tsx
src/pages/customer/CustomerList.tsx

Renamed filterSearch to a more logical name and removing unused functions.

Renamed filterSearch to filterUtil and fixed imports

---

backend/routers/chartTypes.ts
backend/routers/employees/employeeChartConversion.ts
backend/routers/employees/employeesAggregation.ts
backend/routers/employees/employeesRouter.ts

One now targets specific endpoints for getting data to a radar/bar chart for employee specific information.
Extensive description here: [#557](https://github.com/knowit/Dataplattform-issues/issues/557).

Separated endpoints for chart data for employees

---

src/components/filter/FilterUtil.tsx
src/data/DDTable.tsx
src/pages/customer/CustomerFilter.tsx
src/pages/customer/CustomerList.tsx

Fixes [#591](https://github.com/knowit/Dataplattform-issues/issues/591)

Removed motivation filter from `CustomerList`

---

backend/repository/util.ts
backend/routers/employees/aggregationHelpers.ts
src/data/components/table/cells/ProjectStatusCell.tsx

Very small fix. Only changes color and popup text on the traffic lights.

Swithed color for certains statusess in the traffic lights

---

src/pages/customer/CustomerList.tsx

Fixes: https://github.com/knowit/Dataplattform-issues/issues/642

Fix for search bug in customer list

---

apps/server/app.ts
apps/web/src/api/client.ts

Fjernet gamle getters, mest for å trigge deployment

Update stray getters

---

apps/web/src/components/table/cells/ProjectStatusCell.tsx

Updated text for green traffic lights

Updatet text for green traffic lights

---

apps/server/routers/competence/competenceChartConversion.ts
apps/server/routers/competence/competenceRouter.ts
apps/server/routers/employees/employeesTypes.ts

Avhengig av at man legger inn ny rapport i prod:
` 
"name": "countEmployees",
"queryString": "select count(*) as antallAnsatte from dev_level_3_database.cv_partner_employees"
`

ny kategorier for utdanning, annen og ikke registrert #352

---

apps/web/src/components/charts/ChartCard.tsx
apps/web/src/components/skeletons/ChartSkeleton.tsx
apps/web/src/pages/customer/components/CustomerCardList.tsx
apps/web/src/pages/customer/components/CustomerList.tsx
apps/web/src/pages/employee/table/EmployeeTable.tsx

Skeleton layouts skal nå bedre reflektere den ferdig lastede siden

Forbedre skeleton layout

---

apps/web/src/components/gridItem/GridItemContent.tsx
apps/web/src/components/gridItem/GridItemHeader.tsx
apps/web/src/pages/customer/cards/CustomerCard.tsx

Changed font-size and format on customer card to fit new design changes.

Customer card design changes

---

apps/web/package.json
apps/web/src/components/charts/ChartCard.tsx
apps/web/src/components/charts/MultipleChartCard.tsx
apps/web/src/components/charts/SingularChartCard.tsx
apps/web/src/pages/customer/cards/HoursBilledPerWeekCard.tsx
yarn.lock

- La til animasjon på checkboxene for å gjøre det mer åpenbart at de blir flyttet til toppen når de er checket
- Første gang man bruker grafen vil ingen kunden være valgt, noe som kan være litt forvirrende. La derfor til en tekst som forklarer at man må legge til kunder fra listen.

Forbedringer på kundefilter

---

apps/web/src/pages/customer/components/CustomerList.tsx

Rettet typo på sortering av Kunde > Listevisning

Fixed typo in CustomerList

---

apps/web/src/components/header/Header.tsx

Har kun kommentert ut menypunktene, slik at de er lett å sette inn igjen dersom arbeid gjenopptas med undersidene. Har også endra link på knowit-logo til å alltid gå til '/'. Debugsida kan man fortsatt, hvis den skulle trenges, nå på /debug.

Opprydning NavBar

---

apps/web/src/api/data/customer/customerApiTypes.ts
apps/web/src/pages/customer/components/CustomerAccordion.tsx
apps/web/src/pages/customer/components/CustomerList.tsx
apps/web/src/pages/customer/util/search-employees-by-customer.tsx

Super hacky code. I'm so sorry future person git blaming this.

Add a way to sort customer list by both name and number of employees

---

apps/web/package.json
package.json
yarn.lock

PR 462 feiler under deply med denne feilmeldinga:
Error: Cannot find module './dayjs/package.json'
Denne pakka er i bruk i web-modulen, men dayjs ligger kun på toppnivået, ikke i frontend-delen. Har forsøkt å flytte den for å komme det til livs.

Fix build error i PR 462

---

apps/web/package.json
package.json
yarn.lock

Exceljs was put at the wrong place in earlier pr, this fixes

Move exceljs to right place

---

apps/server/routers/employees/aggregationHelpers.ts

What was wrong was that the fileType was set as word instead of docx, easy fix

Fix cv download

---

apps/server/routers/employees/employeesAggregation.ts

Made Math.max(0, value) the 4 places these values got set

Fix negative competence and motivation

---

apps/server/routers/employees/employeesRouter.ts

The wrong report was used to get data for projects last weeks, replaced employeeExperience with employeeCustomers

Fix employee-site crashing

---

serverless.yml

Lagt til ny environment variabel da den ikke fungerte i dev

Lagt til ny environment variabel

---

apps/server/dataplattform/databricksS3Call.ts
apps/server/routers/employees/aggregationHelpers.ts
apps/web/src/components/sortableTable/cells/CustomerStatusCell.tsx

Reverts visibility for sales and admin. Also adds default value 'dev' for environment.

Revert visibility

---

apps/web/src/components/sortableTable/MUITable.tsx
apps/web/src/components/sortableTable/SortableMUITable.tsx
apps/web/src/components/sortableTable/cells/ConsultantCell.tsx
apps/web/src/components/sortableTable/tableTypes.tsx
apps/web/src/pages/employee/EmployeePage.tsx
apps/web/src/pages/employee/table/SortableEmployeeTable.tsx
apps/web/src/pages/organizationStructure/Components/Filter/Filter.tsx
apps/web/src/pages/organizationStructure/Components/Links/LinkElement.tsx
apps/web/src/pages/organizationStructure/Components/NameText.tsx
apps/web/src/pages/organizationStructure/Components/Nodes/EmployeeTreeNode.tsx
apps/web/src/pages/organizationStructure/Components/Nodes/LeaderTreeNode.tsx
apps/web/src/pages/organizationStructure/Components/OrganizationStructureTree.tsx
apps/web/src/pages/organizationStructure/Components/Zooming.tsx
apps/web/src/pages/organizationStructure/OrganizationStructurePage.tsx

Oppdatert org struktur grafen til å ta litt mer plass og lenke til ansatte siden

folk-504 Oppdatert org struktur grafen 

---

apps/web/src/components/charts/nivo/LineChart.tsx
apps/web/src/pages/customer/cards/HoursBilledPerWeekChart.tsx
apps/web/src/pages/customer/customer-overview/CustomerOverview.tsx
apps/web/src/pages/customer/customer-overview/CustomerOverviewFilter.tsx

Når vi tegner legends så har vi ikke tilgang til hvilken farge grafen har valgt å bruke. Det eneste vi vet er rekkefølgen på fargene vi sender til grafen. Dette har jeg nå fikset slik at blir riktig så lenge du bare legger til nye kunder. Men om du fjerner en kunde så vil grafen beholde fargene, men legend vil ikke vite hvilken farge som er fjerna.
Dette må utbedres mer i fremtiden
Har lagt til dato i tooltip ved hover

Fikser noe fargeproblematikk i legend

---

apps/web/src/components/charts/nivo/LineChart.tsx
apps/web/src/components/charts/nivo/common.ts
apps/web/src/pages/customer/cards/CustomerCard.tsx
apps/web/src/pages/customer/cards/HoursBilledPerWeekChart.tsx
apps/web/src/pages/customer/customer-list/CustomerList.tsx
apps/web/src/pages/customer/customer-overview/CustomerHoursPerWeekSection.tsx
apps/web/src/pages/customer/customer-overview/CustomerOverview.tsx
apps/web/src/pages/customer/customer-overview/CustomerOverviewFilter.tsx

Kan nå sortere kunder på kundeansvarlig, og grafen sine farger er mer riktige

Sortering av kunder

---

.github/workflows/deploy-dev.yml
apps/web/src/config.ts
apps/web/src/index.tsx

Ønsker å unngå hardkodete verdier i config bl.a. for variabler relatert til IDer i Cognito, som skal være forskjellig mellom miljøene. I første omgang testes dette kun for dev.
* Lagt inn nye GitHub Secrets for prosjektet.
* Tar i bruk disse secretsene i workflowen til _Deploy Dev_ til å legge dem inn i .env filen i apps/web.
* Disse .env variablene blir deretter brukt i den aktuelle config-filen.
* Også flyttet en variabel for Matomo inn i config fil.

[Fix] Opprette AD-pålogging for Folk.knowit.no 

---

.github/workflows/deploy-dev.yml
apps/web/src/config.ts

Deployingen av Dev fikk feilmelding `The security token included in the request is invalid.`, som betyr at bruken av env contexten i yml-filen ikke fungerer
* Fjernet env-biten i yml-en og setter dem direkte der de skal i stedet.

 [Fix] Opprette AD-pålogging for Folk.knowit.no

---

.github/workflows/deploy-dev.yml

Variablene ser ikke ut til å bli satt i .env-filen. Forsøker å bytte om på hvor variablene settes opp i workflowen
* Setter .env variabler høyere opp i workflowen.
* Byttet om fra å bruke secrets til variabler, da disse variablene ikke er noen secrets.

[Fix] Opprette AD pålogging 

---

.github/workflows/deploy-dev.yml
apps/web/src/config.ts
apps/web/src/index.tsx

Går tilbake til fungerende løsning for dev, hvor verdiene er hardkodet i config-filen. Skal jobbe videre med å finne en løsning for å håndtere disse variablene etter om det er prod eller dev. Løsningen er foreløpig ikke klar til produksjon i dette stadiet.
* Gått tilbake til løsningen fra før forsøkene på å fikse dette problemet

[Fix] Opprette AD innlogging

---

.github/workflows/deploy-dev.yml

Variabel i apps/web/.env ble ikke satt.
Liten endring i scriptet som skriver over variabelen til .env

[Fix] Oppdatert script som kjøres i et steg

---

.github/workflows/deploy-dev.yml
apps/web/src/config/index.ts

Fortsatt ingen variabel lagt til i .env.
* Gjør et forsøkt med å legge på ""

[Fix] Opprette AD pålogging

---

apps/server/routers/employees/aggregationHelpers.ts
apps/server/routers/employees/employeesAggregation.ts
apps/server/routers/employees/employeesRouter.ts

Som et resultat av at listen over de ansatte også inkulderer folk som ikke har startet ennå, så kan det gi et inntrykk av at det er flere som går ledig enn det egentlig er.
* Ny metode som filtrere ut de som har en startdato etter dagens dato.
* Bruker den filtrerete lista for videre rendering av tabellen over de ansatte.

[600 ] Filtrere bort de som ikke har begynt å jobbe - enda

---

apps/server/implementations/azure-openai-llm-repository-impl.ts
apps/server/implementations/ollama-llm-repository-impl.ts
apps/server/repository/llm-repository.ts
apps/server/tests/azure-openai.test.ts
apps/server/tsconfig.json

**What does PR do**
* Added tool support and stream support for AzureOpenAIClient
* Tests that confirm tool use works as well as stream
**What to consider**
* Should only flesh out already accepted AzureOpenAI client, making flow for future LLM clients understandable
* If it is not understandable as an outsider, it should be documented better (at least the LLMClient itself, how the implementations does it should not be important)
*

More tests for LLMClient

---

apps/server/tests/azure-openai.test.ts
apps/server/tsconfig.json

**What does PR do**
* hopefully fixes broken dependency tree so it finds jest at correct place

Typeroots should be unnecessary

---

apps/server/tsconfig.json

Both Jest and running yarn server:dev:local  
works

Fixed issue

---

apps/server/README.md
apps/server/implementations/chroma-rag-repository-impl.ts
apps/server/package.json
apps/server/repository/rag-repository.ts
apps/server/tests/chromadb.test.ts
yarn.lock

**What does PR do**
* Adds basic RAG contract that can be used for other RAG implementations
* Adds simple ChromaDB implementation for local testing and/or remote use if we end up using that. Mostly to confirm contract is valid
* Adds test suite for ChromaDB to doubly confirm contract. Requires chromadb running locally on port 8000
**What to consider**
* Are there missing pieces of the RAG contract that might be needed
* Are there other implementations that would be more fitting for test locally?

Added chromaDB and RAG contract

---

apps/server/README.md
apps/server/implementations/repositories/postgres-chat-repository.ts
apps/server/repository/chat-repository.ts
apps/server/routers/databaseRouter.ts

* Ønsket funksjonalitet som gjør at chat_messages slettes dersom de tilhører en chat som blir slettet.
* Flere endepunkter
* Mindre refaktorering
* Definert en Foreign Key i chat_messages med constrainten CASCADE ON DELETE.
* Enklere oppsett av tabellene i en Postgres database med et setup-endepunkt. Krever at den databasetilkobling er oppe. Kan da bare kjøre endepunktet for å sette opp tabellene.
* Oppdatert README.md

[Feature] Databricks #138 - Improve table relations in database

---

apps/web/src/components/header/Header.tsx
apps/web/src/pages/knowitGPT/components/ChatWindow.tsx

Add darkmode for the chat
Add autoscrolling
Adjust headersize for the tabs

Darkmode, scroll and headersize

---

apps/server/implementations/repositories/postgres-chat-repository.ts
apps/server/routers/databaseRouter.ts
apps/web/src/api/client.ts
apps/web/src/api/data/database/databaseApi.ts
apps/web/src/api/data/database/databaseQueries.ts
apps/web/src/api/data/database/databaseTypes.ts
apps/web/src/pages/knowitGPT/components/ChatLog.tsx
apps/web/src/pages/knowitGPT/components/ChatWindow.tsx

Add connections to the postgres database
Fix error of postgres database crashing after 4 post-calls
Create endpoints to database in web
Make the chatgpt post messages and chats to the database
Create an overview of user's old chats so that those can be accessed

Knowit gpt chathistory

---

apps/server/implementations/repositories/dynamodb-chat-repository.ts
apps/server/repository/chat-repository.ts
apps/server/routers/databaseRouter.ts
apps/web/src/api/data/database/databaseApi.ts
apps/web/src/api/data/database/databaseQueries.ts
apps/web/src/api/data/database/databaseTypes.ts
apps/web/src/pages/knowitGPT/components/ChatLog.tsx
apps/web/src/pages/knowitGPT/components/ChatWindow.tsx

Make adjustments so that the ai still will work after implementation of dynamodb

Make knowitgpt work with dynamodb
