knowit/folk-webapp

src/components/EmployeeInfo.tsx

Fra Trent: "Ser at innholdsteksten i utvidet konsulentfelt er implementert i 14px. Men det skal være 12px med 16px line-height som angitt i prototypen"

set fontSize to 12px in expanded consultantcell

---

src/components/EmployeeInfo.tsx
src/pages/EmployeeSite.tsx

For å løse [Issue #312](https://github.com/knowit/Dataplattform-issues/issues/312) midlertidig(?). 
Endret til **Beregnet arbeidserfaring** og la til en enkel tooltip som forklarer hvordan det er hentet

added tooltip and changed label

---

backend/repository/data.js
src/data/components/Sunburst.tsx
src/pages/Competence.tsx

Første del av [issue #351](https://github.com/knowit/Dataplattform-issues/issues/351). 
> Endringer ønskes:
>Vise relativ størrelse på et komptetanseområde ved søylestørrelse
>Vise antall som har gitt seg selv >3 i score og/eller precentilscore på samme måte som radar-grafen
Hvordan vi skal løse resten må diskuteres

added bar-visualization for competence mapping data

---

src/components/EmployeeInfo.tsx
src/pages/EmployeeSite.tsx

Upgrading the frontend dependencies led to stricter handling of linter warnings. They are now treated as errors in the CI build process, blocking the build and deployment of the frontend. This PR fixes the two linter warnings currently in the frontend code.

Hotfix: Fixes for linter warnings (blocking deployment)

---

package.json
yarn.lock

Added safe versions of `is-svg` and `ssri` to the resolution dependencies.
Also bumped minor/patch version for other outdated dependencies in frontend.

Fixes for security issues with dependencies

---

backend/yarn.lock
yarn.lock

This is the result of running `yarn upgrade-interactive` in both the webapp and backend, and picking only dependencies with patch- and minor updates.

Update dependencies in webapp and backend

---

src/LoginProvider.tsx

feil i dev som gir feilmeldingen: {"message":"Internal Server Error"}
når jeg prøvde å kjøre det lokalt fikk jeg feilmelding om at typer i cookiene ikke eksisterte.
ble fikset etter jeg fjernet initial object key for cookies

feil i dev

---

src/components/EmployeeInfo.tsx
src/data/components/table/DataTable.tsx

Ved fiksing av pr kommentarer ble de lagt til en dependency i useEffecten som gjør at expandedrows ikke fungerer og crasher nettsiden.

Fixing the expanded rows error

---

README.md
package.json
src/setupProxy.js

* Also set the correct `proxy` URL in `package.json` so that running frontend locally (using `yarn:start`) works without having to run backend locally as well.
Issue: https://github.com/knowit/Dataplattform-issues/issues/564

Improved onboarding documentation

---

.github/workflows/backend.yml
.github/workflows/frontend.yml

The path patterns defined for triggering GitHub Actions on pull requests were not matching correctly. 
* All PRs triggered the frontend workflow, even if changes only were made in the `backend` folder.
* PRs with changes in files located at the root of the `backend` folder (e.g. in the `backend/package.json` file) did not trigger the backend workflow. Only changes made in subfolders of the `backend` folder triggered this workflow.
See the workflows here: https://github.com/knowit/folk-webapp/actions (defined in the `.github` folder in the project)
The changed patterns should (hopefully) work as follows:
* PRs that contain changes in the `backend` folder should trigger the backend workflow
* PRs that contain changes outside the `backend` folder should trigger the frontend workflow
* PRs …

Fixed path patterns that should trigger pull request workflows

---

backend/repository/data.ts
backend/repository/util.ts
backend/routers/employees/aggregationHelpers.ts
backend/routers/employees/employeesAggregation.ts
backend/routers/employees/employeesTypes.ts
backend/routers/handler.ts
src/pages/EmployeeProfile.tsx

This PR primarily fixes an issue for cases where an employee is not related to any customers. The aggregated result was an array with a single empty object. This is now changed so that the return value is an empty array.
In addition, v1 of the API now returns a 404 response for `employeeProfile` if an employee is not found. This will make the error handling easier on the frontend side while we wait for v2 of the API.
Also made a few related changes:
* Finding the customer with the highest weight for an employee is now extracted as a separate, more robust function.
* The mapping of "tags" is also extracted as a separate function.
* The aggregation for the `employeeCompetence` endpoint is simplified (while giving the same result).
The changes made to the API is also transferred to v2.

`employeeProfile` endpoint issues

---

src/data/components/table/DataTable.tsx
src/data/components/table/cells/CheckBoxHeaderCell.tsx
src/data/types.tsx

Fixes [#605](https://github.com/knowit/Dataplattform-issues/issues/605)
The problem was that the state of expanded rows was located in the `DataTable` component. Every time the state changed (a row expanded/collapsed), the entire `DataTable` component was re-rendered. This lead to a reset of scrolling state in the react-virtualized table (a child of the `DataTable` component).
A quickfix was to separate the react-virtualized components into its own component, `VirtualizedTable`, and keep the state there. (We might want to think about restructuring the table components more, and maybe adjust how we use react-virtualized. But that is out of scope for this bugfix.)
I also made some adjustments to this separated component to improve legibility, consistency and robustness.

Fix for scrolling reset in `EmployeeTable`

---

src/components/filter/FilterUtil.tsx
src/data/DDTable.tsx
src/data/types.tsx
src/pages/customer/CustomerList.tsx
src/pages/employee/components/EmployeeTable.tsx

Fixes [#614 ](https://github.com/knowit/Dataplattform-issues/issues/614) + some improvements to search functionality.
* Added `getSearchValue` function for the job title column, thus including it in the search values. 
* Fixed the `GetSearchValueFn` type so that it reflects the uncertainty of the real world.
* Removed redundant `searchable` property from column type.
Also refactored the searching functionality:
* more robust for unknown values
* support for multi-word searches, across columns

Include job title in search for employee table

---

backend/routers/competence/competenceAggregation.ts
backend/routers/competence/competenceChartConversion.ts
backend/routers/customer/customerRouter.ts
src/api/client.ts
src/api/data/chartResponses.ts
src/api/data/competence/competenceApi.ts
src/api/data/competence/competenceQueries.ts
src/api/data/customer/customerApi.ts
src/api/data/customer/customerQueries.ts
src/api/data/employee/employeeApi.ts
src/api/data/employee/employeeQueries.ts
src/pages/Debug.tsx

Oppdaterer `API` frontend til å reflektere endringene som har blitt gjort backend. Primært lages det enedpunkter/hooks for kall på chart-data som skal brukes i Nivo.
En del av API-urlene blir nå lange og stygge, men dette vil bli fikset når man er 100% på v2.
Så vidt jeg kan se nå, så er det nå klart for at frontenden kan skrives om til å bruke det nye APIet for fullt. 
På sikt kan mao alle SWR hooks og under-the-hood-getters som brukes for å opprettholde funksjonalitet, fjernes.
Extensive description here: [#557](https://github.com/knowit/Dataplattform-issues/issues/557).

Oppdater frontend API med hensyn på nye backend-endringer

---

src/components/filter/FilterHeader.tsx
src/components/filter/FilterUtil.tsx
src/data/DDTable.tsx
src/data/components/table/DataTable.tsx
src/pages/employee/components/EmployeeTable.tsx

Fixes [#570](https://github.com/knowit/Dataplattform-issues/issues/570) where the filters in the employee table did not work correctly because the index used when mapping competence and motivation columns was off by one. Converted the mapping type to an enum for better/simpler type safety.
Also made a couple of minor improvements to the employee table:
* added display labels for the filters (shown when a filter is active)
* fixed a problem where the table would not render correctly if the user sorted the table while a row was expanded

Fix for filtering bug #570

---

backend/repository/data.ts
backend/repository/reports.js
backend/routers/customer/customerAggregation.ts
backend/routers/customer/customerRouter.ts
backend/routers/customer/customerTypes.ts
backend/routers/employees/aggregationHelpers.ts
backend/routers/employees/employeesAggregation.ts
backend/routers/employees/employeesTypes.ts
src/api/data/customer/customerApi.ts
src/api/data/customer/customerApiTypes.ts
src/api/data/customer/customerQueries.ts
src/api/data/employee/employeeApiTypes.ts
src/components/filter/FilterUtil.tsx
src/components/gridItem/GridItem.tsx
src/components/gridItem/GridItemHeader.tsx
src/data/DDTable.tsx
src/data/components/RowCount.tsx
src/data/components/table/DataTable.tsx
src/data/types.tsx
src/pages/customer/CustomerAccordion.tsx
src/pages/customer/CustomerFilter.tsx
src/pages/customer/CustomerList.tsx
src/pages/customer/util/searchEmployeesByCustomer.tsx
src/pages/employee/components/CvDownloadList.tsx
src/pages/employee/components/EmployeeInfo.tsx
src/pages/employee/components/EmployeeTable.tsx
src/tests/EmployeeInfo.test.tsx
src/utils/cvLinkHelpers.ts

Created a new report (`employeesWithPrimaryCustomer`) and separate endpoint (`emplyeesByCustomer`) for the customer list ([#619](https://github.com/knowit/Dataplattform-issues/issues/619)). Only necessary data is fetched, reducing the latency caused by data transfer and aggregation/processing that was a problem when using the `employeeTable` endpoint.
* Employees without customers are not included in the report (fixes [#590](https://github.com/knowit/Dataplattform-issues/issues/590))
* The new endpoint returns employees grouped by customer – made it easy to implement a filtering counter (fixes [#618](https://github.com/knowit/Dataplattform-issues/issues/618))
* Reduced need for data processing in the frontend (fixes bug in [#616](https://github.com/knowit/Dataplattform-issues/issues/616)) …

Improvements to customer list

---

backend/repository/reports.js

* The `employeesWithPrimaryCustomer` report is used by the customer list, that groups employees by their primary customer. 
* This fix considers that an employee can have multiple customers with a weight of 1 (aka. the primary customer). This is because the weight is generated on each ingestion from UBW, and data from the four previous periods (with old, previously generated weights) is retained.
* We now select the most recent weight.
The report is already updated in the dev. environment, this PR is just to document the change.

Updated `employeesWithPrimaryCustomer` report to check for latest timestamp

---

apps/web/src/components/charts/nivo/BarChart.tsx

La til en sjekk ved beregning av y-akse på `BarChart.tsx` slik at den aldri er 0.

Bug med BarChart på kompetanseside

---

apps/web/src/components/charts/SingularChartCard.tsx
apps/web/src/pages/customer/cards/HoursBilledPerCustomerCard.tsx
apps/web/src/pages/customer/cards/HoursBilledPerWeekCard.tsx

PR for [#702](https://github.com/knowit/Dataplattform-issues/issues/702) og en videreføring (duplikat?) av [#657](https://github.com/knowit/Dataplattform-issues/issues/657) for å filtrere på perioder på kundesiden.
Implementasjonen innebærer å servere `findFilteredData` med riktig liste av reg_periods, basert på valgt filter.
F.eks hvis dagens dato er 19. november 2021, og '_Siste måned_' er valgt, filtreres dataen fra første uke i november -> `['202144', '202145', '202146']`
**NB**: Per nå brukes `overrideDate` i `SingularChartCard` for å definere spesifikk dato slik at perioder med dev data gir mening (13. November 2021). Denne må fjernes før pull til master, evnt bør vi få inn noe mer gjeldende dev data.

Periode filter på kundesiden/overordnet oversikt

---

apps/web/src/components/SearchInput.tsx
apps/web/src/pages/customer/components/CustomerFilter.tsx
apps/web/src/pages/customer/components/CustomerList.tsx

Før var søkeverdien kun lagret i SearchInput, som gjorde at man ikke kunne beholde staten når man byttet tabs på kundesiden. Nå kan man sende inn verdi fra useState i parent komponent. Litt ekstra logikk måtte til for å observere verdien fordi den er er debouncet.

Gjør det mulig å sende inn nåværende søkeverdi til SearchInput

---

apps/server/routers/customer/customerAggregation.ts

Plutselig dukket det opp internal server error i prod. I Cloudwatch står det : `employeeCustomer.reg_periods.split is not a function`
Vi antar at det av en eller annen grunn da er kommet inn en tom liste som den ikke klarer å ta split på, så da legger vi ved sjekk for dette

Fikse internal server error for prod grunnet undefined liste

---

apps/web/src/components/Content.tsx

Grunnet mangel på data så gjør vi siden utilgjengelig frem til den er tilstrekkelig testet med data fra prod. For øyeblikket så får ikke strukturen plass i bildet, så her må det testes videre lokalt først

Gjøre organisasjons-side utilgjengelig inntil videre

---

apps/server/routers/customer/customerChartConversion.ts
apps/web/src/components/charts/ChartCard.tsx
apps/web/src/components/charts/SingularChartCard.tsx
apps/web/src/components/charts/nivo/LineChart.tsx
apps/web/src/pages/customer/cards/HoursBilledPerWeekCard.tsx
apps/web/src/pages/customer/components/HoursBilledPerWeekTooltip.tsx

Dersom en kunde har timer for en gitt uke, vil nå dataserien for alle kunder ha den uka. Dersom en kunde ikke hadde noen timer i den perioden vil dataen bli satt til 0. For å kompensere for flere punkter i tooltip blir disse filtrert bort fra tooltip. Vi kunne også vurdert å sortert og begrenset antall kunder i tooltip, men det får bli i neste omgang.

Fiks usortert x-akse på "Timer brukt per periode" grafen

---

apps/web/src/App.tsx
apps/web/src/context/UserInfoContext.tsx

A returning user will have a previously set access token in localStorage. If such a token is present we let the UserInfo remain in undefined state for up to 3 seconds to allow the user info to be fetched.
For users that were not logged in in previous session we transition from undefined to null immediately and serve the login page.

Remove flash of login screen for logged in users

---

apps/server/routers/authRouter.ts
apps/web/src/App.tsx
apps/web/src/context/UserInfoContext.tsx

Fjerner et ekstra tilfellet av å se login siden når man ikke skulle. Legger til login=true i URL når man blir redirectet fra authRouter, App komponenten detekterer dette og setter en egen localStorage item for dette (istedet for å bruker access token), og sletter så login=true fra URLen.
Før:
Ettter

Remove login flash after completed login by using parameter on redirect

---

apps/web/src/components/charts/chartFilters/useFilteredData.ts
apps/web/src/components/charts/chartFilters/usePerWeekFilter.ts
apps/web/src/pages/customer/cards/HoursBilledPerWeekCard.tsx
apps/web/src/pages/customer/components/CustomerOverview.tsx

Adds a customer filter on the graph (the state is in the customer overview page, so it can be used for the customer cards also in the future).
Also removes the usePerWeekFilter from the common useFilteredData to memoize the data.

Add customer filter to HoursBilledPerWeek graph

---

apps/web/src/components/filter/FilterInput.tsx

Fant følgende i migreringsdokumentasjonen for oppgradering til MUI 5:
> renderOption should now return the full DOM structure of the option.
I eksempelet for hvordan "recover from the change" hadde de brukt lister, og importert props på liste-elementet. Gjorde det samme i koden hos oss, og ser ut til at det virker nå.

Changed renderOption to li, added props

---

apps/server/package.json
apps/server/repository/util.ts
yarn.lock

xml2js er i bruk i 2 forskjellige versjoner av aws-sdk. Den ene har vi installert selv, og den er bumpet med denne PRen. Med oppdateringen, kommer det noen justeringer i syntax, bl.a. importer fra pakka. Den importsyntaxen er også oppdatert i denne PRen, slik at den ikke skal plage oss seinere.
Nevnt i #472

Bumped aws-sdk version and adjusted import

---

apps/web/src/components/charts/chartFilters/usePerWeekFilter.ts

The problem in this bug was that the monthValues wasn't added together, such that the last value of the month would be the one that counted. I provided this adding

Fix monthly hours billed graph for month

---

apps/web/src/components/SearchInput.tsx
apps/web/src/pages/organizationStructure/Components/Links/LinkElement.tsx
apps/web/src/pages/organizationStructure/Components/Links/Links.tsx
apps/web/src/pages/organizationStructure/Components/Nodes/EmployeeTreeNode.tsx
apps/web/src/pages/organizationStructure/Components/Nodes/LeaderTreeNode.tsx
apps/web/src/pages/organizationStructure/Components/OrganizationStructureTree.tsx
apps/web/src/pages/organizationStructure/LeadersOverview.tsx
apps/web/src/pages/organizationStructure/OrganizationStructurePage.tsx

Gi mulighet til søke etter en ansatt i orgstruktur for så å få markert bekreftede søkeresultater i bold (bygger på Maries pr så kan være greit gjøre det ferdig først)

Orgstruktur search for employees

---

apps/server/routers/employees/employeesAggregation.ts
apps/web/src/components/sortableTable/SortableMUITable.tsx
apps/web/src/components/sortableTable/tableTypes.tsx
apps/web/src/pages/employee/table/SortableEmployeeTable.tsx

Søkeverdien som ble sendt inn førte data over fra EmployeeRow til ønsket element når det egt var EmployeeTableRow man burde se på. Lagt til nytt element searchValue som overfører mellom riktige verdier

Fix blank screen when employee-search

---

apps/server/routers/employees/aggregationHelpers.ts
apps/server/routers/employees/employeesAggregation.ts
apps/server/routers/employees/employeesTypes.ts
apps/web/src/api/data/employee/employeeApiTypes.ts
apps/web/src/components/filter/FilterUtil.tsx
apps/web/src/components/sortableTable/cells/CustomerStatusCell.tsx
apps/web/src/components/sortableTable/cells/ProjectStatusCell.tsx
apps/web/src/pages/employee/table/SortableEmployeeTable.tsx

Added new category NOT_BILLABLE for CEO, Admin and Sales, will show role in Kunde-row. They will not be included when clicking "Vis bare ledige"

Added role to employee info

---

apps/server/package.json
apps/server/repository/util.ts
yarn.lock

Filene som genereres er for store for opplasting til AWS lambda, og vi må derfor rydde opp litt i dependencies for å spare plass

Fjerne dependency for plassparing

---

apps/server/dataplattform/databricksS3Call.ts

Koden endres for å kunne bruke mapper under s3 bucket for å skille mellom prod og dev.

Legge til rette for kjøring mot environment-mapper i s3 bucket

---

apps/web/src/components/charts/nivo/LineChart.tsx

Adds labels on the X-axis of the customer line-graph.
Its set up to responsively add the number of labels by the amount of data to prevent cluttering, but it will max out at 6 or 7.
You can change this amount by changing the number in the `tickInterval` variable.

#549 - added responsive ticks to the bottom of customer billing graph

---

apps/web/src/pages/employee/table/SortableEmployeeTable.tsx

Sortering av ansatte på tittel og kunde fungerte ikke i oversikten over ansatte for kunder i listevisningen.
Dette var fordi variabelen som ble brukt som sorteringsverdi for de kolonnene ikke var riktig.
Endret variabelen til å komme fra EmployeeCustomerRow.

[Bugfix] Fikset feil variabel brukt som sortValue i listevisning.

---

apps/web/src/pages/organizationStructure/Components/NameText.tsx

I organisasjonsstrukturen var det ønsket at et kort med noe informasjon ble vist, med mulighet til å navigere til siden for den ansatte. For øyeblikket blir man sendt direkte til den ansatte sin siden dersom man trykker på navnet til personen.
For å style kortet har jeg tatt i bruk MUI sin styled() utility for å style componenter.
* Laget et styled component per inndeling av kortet.
* For å hente profilbildet bruker jeg hooken useEmployeeProfile() for å huke tak i bilde-url'en.

[Feature] Ny ansattkort-popup i organsisasjonsstrukturen

---

apps/web/src/components/Content.tsx
apps/web/src/components/charts/ChartDisplayOptions.tsx
apps/web/src/components/charts/DropdownPicker.tsx
apps/web/src/components/charts/MultipleChartCard.tsx
apps/web/src/components/charts/SingularChartCard.tsx
apps/web/src/components/charts/ToggleBigChartButton.tsx
apps/web/src/components/header/NavTab.tsx
apps/web/src/index.tsx
apps/web/src/pages/competence/CompetencePage.tsx
apps/web/src/pages/customer/CustomerPage.tsx
apps/web/src/pages/customer/CustomerSitePage.tsx
apps/web/src/pages/customer/cards/HoursBilledPerWeekChart.tsx
apps/web/src/pages/customer/customer-list/CustomerList.tsx
apps/web/src/pages/customer/customer-overview/CustomerCardSort.tsx
apps/web/src/pages/customer/customer-overview/CustomerHoursPerWeekSection.tsx
apps/web/src/pages/employee/EmployeePage.tsx
apps/web/src/pages/employee/EmployeeProfilePage.tsx
apps/web/src/pages/employee/table/EmployeeTableWithFilter.tsx
apps/web/src/pages/login/LoginPage.tsx
apps/web/src/pages/organizationStructure/OrganizationStructurePage.tsx
apps/web/src/pages/other/DebugPage.tsx
apps/web/src/pages/other/UnderConstructionPage.tsx

Skal forbedre Matomo dashboards og ha flere muligheter til å lage egne _custom reports_ som kan brukes i dashboardet.
* Oppdatert tracking av besøk på sider. Kodesnutten som tracker siden blir gjort på den spesifikke siden, i stedet for å ha koden et sted som håndterer det for alle sidetyper. Dette har jeg gjort for å åpne opp for egendefinerte verdier i trackingen og gi nye utviklere en synligere kobling til Matomo slik at det blir enklere for dem å huske at de også må forholde seg til det.
* Lagt til flere events som blir tracket bl. a: klikk for å endre visningen på _Kunder_-siden, klikk for å filtrere og sortere tabeller eller lister.
* Noen av trackerne tar i bruk _titles_ og _labels_ som de var via props for å ha mer detaljer i noen av trackerne.

[486] Matomo tracking oppdateringer

---

apps/server/routers/authRouter.ts
apps/web/package.json
apps/web/src/App.tsx
apps/web/src/api/client.ts
apps/web/src/components/Content.tsx
apps/web/src/components/LoginLogoutButton.tsx
apps/web/src/components/header/Header.tsx
apps/web/src/config.ts
apps/web/src/context/UserInfoContext.tsx
apps/web/src/hooks/useUserInfo.ts
apps/web/src/index.tsx
apps/web/src/pages/login/LoginPage.tsx
serverless.yml
yarn.lock

Ønske om å gå vekk fra Google som identity provider og i stedet bruke Azure AD/Entra ID
* Byttet ut gammel autentiseringsflow gjennom OpenID-klient til Amplify. Wrappet appen i en `<Authenticator.Provider>`
* Fjernet `client_secret` som nå er obsolete.
* Tar i bruk imports fra Amplify, i.e. `fetchAuthSession()` og `signInWithRedirect()` til å håndtere innlogging, utlogging og access token. 
* Bruker nå `LoginLogoutButton.tsx` i headeren og i login siden, i stedet for at det er to ulike løsninger for dette.
* Refaktorert koden relatert til UserInfoContext til å bli en context-fil og en hook.
* Refaktorert ut HeaderTabs til en function component.
* Generell opprydding i filer det er arbeidet på, som f. eks. imports.

[9] Opprette AD-pålogging for Folk.knowit.no

---

apps/web/src/config.ts

Får feilmelding om at Amplify Auth ikke er konfigurert. Tror muligens dette skyldes krøll med redirect URLene som settes gjennom en `NODE_ENV` sjekk,
Inkluderer alle mulige redirect URLer, som ser ut til å fungere lokalt.

Changed redirect url to include all possible redirect urls for the app

---

.github/workflows/deploy-dev.yml
apps/web/src/index.tsx

Forsøk på å løse feilmeldingen fra Amplify Auth konfigurasjonen.
* Forsøker å sette variablene i .env direkte i skriptet, i stedet for å bruke working-directory. Dvs. legge til `apps/web` før `.env`
* Legger til en console log for debugging. Skal brukes til å dobbeltsjekke at variabelen er satt før konfigurasjonen. Skal slettes.

[Fix] Opprette AD pålogging

---

.vscode/launch.json
apps/web/src/context/UserInfoContext.tsx

I produksjon ble ikke profilbildet til den innloggede brukeren hentet.
* Henter employeeProfile-data i den samme useEffecten som userInfo blir hentet, i stedet for å håndteres det i to ulike useEffects. Unødvendig når den ene useEffecten er avhengig av resultatet fra kallet som henter userInfo.
* Også oppdatert launch.json, fordi webRoot definert der var feil.

[597-Fix] Profilbilde i header

---

apps/server/routers/customer/customerAggregation.ts
apps/server/routers/customer/customerTypes.ts

Issue: [#580](https://github.com/orgs/knowit/projects/9/views/1?pane=issue&itemId=66397785)
I listevisningen under 'Kunder' på nettsiden dukker det ikke opp navn på konsulenter som jobber hos en kunde.
Fix: JSON-filen fra AWS bruker 'name', ikke 'navn' for navn på ansatte, så bruk av 'navn' i frontend-koden har vært en bug som nå blir rettet opp.

#580: Navn på ansatte i listevisningen under Kunder

---

apps/server/routers/employees/employeesAggregation.ts

Når de ansatte skal filtreres på startdato, brukes en rapport for filtreringen. I denne rapporten er det ikke alle ansatte er i, pga diverse, som gjør at de forsvinner i filtreringen selv om de ikke skal det.
Sjekker om filtreringsfunksjonen returnerer null. Dersom den gjør det, tas fortsatt den ansatte med i listen som vises på forsiden. De som har en fremtidig sluttdato blir da ikke med i listen, og så må de som evt har sluttet med fortsatt står på listen vente til AD/Simployer har håndtert det hos seg.

[Fix] 600 Filtrere bort de som ikke har begynt å jobbe

---

apps/web/eslint.config.mjs

Alle api-kallene i web klager over manglende retur-typer, slår av eslint-warnings for disse

Turn off some eslint-warnings

---

apps/server/implementations/azure-openai-llm-repository-impl.ts
apps/server/implementations/python_app-llm-repository-impl.ts
apps/server/repository/llm-repository.ts
apps/web/src/api/data/llm/llmQueries.ts

**What does PR do**
* Adds a simple implementation of LLMClient that interfaces another endpoint
* This is in order for that endpoint (a proposed python backend) should handle all the actual dealings from messages to actual context creation for LLM and calling the LLM after RAG and context refinement is complete
* When that backend is complete it returns to this implementation and we can simply output the messages
* Removed generateEmbeddings as abstract method as not all potential implementations want to use it

Temp python backend intermediary for KnowitGPT

---

apps/server/README.md
apps/server/implementations/repositories/dynamodb-chat-repository.ts
apps/server/implementations/repositories/postgres-chat-repository.ts
apps/server/package.json
apps/server/repository/chat-repository.ts
apps/server/routers/databaseRouter.ts
yarn.lock

Chat history skal håndteres i DynamoDb satt opp i AWS.
Denne skal interageres via endepunkt. 
* I AWS er det laget en DynamoDb for development miljøet. Denne ligger under kontoen `knowit-dataplattform-dev`.
* Oppdatert signaturene for chat-repository interfacet for å kunne effektivt bruke `partition_key` og `sort_key`. Dette gjør at standard SQL-databaser (dersom man skal bruke det) tar inn et ekstra argument enn nødvendig.
* Slettet setup endepunkt for PostgresSQL lokalt.
* Oppdatert README om DynamoDb og fjernet dokumentasjon om PostgresSQL.

[databricks-139] AWS DynamoDb implementasjon for chat history
